### ISSUE TITLE
[bug] sfpegNavigationMenuCmp - Wrong title on list items upon hover

### ISSUE THREAD

**Issue by brave-hawk** [pegros/PEG_LWR#2]
**Describe the bug**
When we hover over the links, the wrong title is displayed (tooltip)
![image](https://github.com/user-attachments/assets/76ae21c5-e0a5-4f01-aee4-22cdc8d89502)

**To Reproduce**
1. Go to a page with the nav menu items
2. Hover over a link to a page
3. See wrongly displayed text

**Expected behavior**
Expected the tooltip to say: "Ouvrir la page M'enregistrer"

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome

**Additional context**
Suggested fix:
In line 114, we should have:
```javascript
newItem.title = this.titlePrefix + ' ' + item.label;
```

**Comment by pegros** [comment]
Thanks @brave-hawk for finding the issue.
I shall push a fix ASAP.

**Comment by pegros** [comment]
Problem fixed as proposed.
Thanks @brave-hawk

**Comment by pegros** [comment]
Error when pushing commit  [0988a85](https://github.com/pegros/PEG_LWR/commit/0988a8502acd5c0074ddcc31513f371f73b92f6c) which is actually related to #3
